version: "3.9"

services:
  db-freelancer:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: 123456
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db-freelancer
    depends_on:
      - db-freelancer
volumes:
  db_data: {}

#docker compose up -d